---
name: Python package

"on": [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install 'uv==0.9.1'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv sync
      - name: Check formatting with ruff format
        run: |
          uv run ruff format --check .
      - name: Check import ordering with ruff
        run: |
          uv run ruff check --output-format=github --select I .
      - name: Check static typing with mypy
        run: uv run mypy .
      - name: Lint with ruff
        run: |
          uv run ruff check --output-format=github .
